package io.a2a.spec;

import java.util.List;
import java.util.Map;

import io.a2a.util.Assert;
import org.jspecify.annotations.Nullable;

/**
 * Represents a file, data structure, or other resource generated by an agent during task execution.
 * <p>
 * Artifacts are outputs created by agents in response to user requests. They can represent various
 * types of content including documents, data structures, analysis results, generated files, or any
 * other structured output from agent operations.
 * <p>
 * Each artifact has a unique identifier and contains content through {@link Part}s, which allow
 * for multi-modal output (text, files, structured data). Artifacts can include metadata for
 * additional context and support protocol extensions.
 * <p>
 * Artifacts are typically delivered to clients through {@link Task} responses or
 * {@link TaskArtifactUpdateEvent} events in streaming scenarios.
 * <p>
 * This class is immutable. Use the {@link Builder} for construction.
 *
 * @param artifactId the unique identifier for this artifact (required)
 * @param name the human-readable name of the artifact (optional)
 * @param description a brief description of the artifact's purpose or content (optional)
 * @param parts the content parts comprising the artifact (required, must not be empty)
 * @param metadata additional key-value metadata for the artifact (optional)
 * @param extensions protocol extensions used in this artifact (optional)
 * @see <a href="https://a2a-protocol.org/latest/">A2A Protocol Specification</a>
 */
public record Artifact(String artifactId, @Nullable String name, @Nullable String description, List<Part<?>> parts, @Nullable Map<String, Object> metadata,
                       @Nullable List<String> extensions) {

    /**
     * Compact constructor that validates required fields.
     *
     * @param artifactId the artifactId parameter (see class-level JavaDoc)
     * @param name the name parameter (see class-level JavaDoc)
     * @param description the description parameter (see class-level JavaDoc)
     * @param parts the parts parameter (see class-level JavaDoc)
     * @param metadata the metadata parameter (see class-level JavaDoc)
     * @param extensions the extensions parameter (see class-level JavaDoc)
     * @throws IllegalArgumentException if artifactId or parts is null, or if parts is empty
     */
    public Artifact {
        Assert.checkNotNullParam("artifactId", artifactId);
        Assert.checkNotNullParam("parts", parts);
        if (parts.isEmpty()) {
            throw new IllegalArgumentException("Parts cannot be empty");
        }
    }

    /**
     * Create a new Builder
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Create a new Builder initialized with values from an existing Artifact.
     * <p>
     * This builder creates defensive copies of mutable collections to ensure
     * that modifications to the builder do not affect the original Artifact.
     *
     * @param artifact the Artifact to copy values from
     * @return the builder
     */
    public static Builder builder(Artifact artifact) {
        return new Builder(artifact);
    }

    /**
     * Builder for constructing immutable {@link Artifact} instances.
     * <p>
     * The Builder provides a fluent API for creating artifacts with required and optional fields.
     * Artifacts must have an artifactId and non-empty parts list.
     * <p>
     * Example usage:
     * <pre>{@code
     * Artifact result = Artifact.builder()
     *     .artifactId("artifact-123")
     *     .name("Analysis Report")
     *     .description("Detailed analysis of user data")
     *     .parts(List.of(new TextPart("Report content...", null)))
     *     .build();
     * }</pre>
     */
    public static class Builder {
        private @Nullable String artifactId;
        private @Nullable String name;
        private @Nullable String description;
        private @Nullable List<Part<?>> parts;
        private @Nullable Map<String, Object> metadata;
        private @Nullable List<String> extensions;

        /**
         * Creates a new Builder with all fields unset.
         */
        private Builder(){
        }

        /**
         * Creates a new Builder initialized with values from an existing Artifact.
         *
         * @param existingArtifact the Artifact to copy values from
         */
        private Builder(Artifact existingArtifact) {
            artifactId = existingArtifact.artifactId;
            name = existingArtifact.name;
            description = existingArtifact.description;
            parts = existingArtifact.parts;
            metadata = existingArtifact.metadata;
            extensions = existingArtifact.extensions;
        }

        /**
         * Sets the unique identifier for this artifact.
         *
         * @param artifactId the artifact identifier (required)
         * @return this builder for method chaining
         */
        public Builder artifactId(String artifactId) {
            this.artifactId = artifactId;
            return this;
        }

        /**
         * Sets the human-readable name of the artifact.
         *
         * @param name the artifact name (optional)
         * @return this builder for method chaining
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * Sets a brief description of the artifact's purpose or content.
         *
         * @param description the artifact description (optional)
         * @return this builder for method chaining
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /**
         * Sets the content parts comprising the artifact.
         *
         * @param parts the list of content parts (required, must not be empty)
         * @return this builder for method chaining
         */
        public Builder parts(List<Part<?>> parts) {
            this.parts = parts;
            return this;
        }

        /**
         * Sets the content parts from varargs.
         *
         * @param parts the content parts (required, must not be empty)
         * @return this builder for method chaining
         */
        public Builder parts(Part<?>... parts) {
            this.parts = List.of(parts);
            return this;
        }

        /**
         * Sets additional metadata for the artifact.
         *
         * @param metadata map of metadata key-value pairs (optional)
         * @return this builder for method chaining
         */
        public Builder metadata(@Nullable Map<String, Object> metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Sets the list of protocol extensions used in this artifact.
         *
         * @param extensions the list of extension identifiers (optional)
         * @return this builder for method chaining
         */
        public Builder extensions(@Nullable List<String> extensions) {
            this.extensions = (extensions == null) ? null : List.copyOf(extensions);
            return this;
        }

        /**
         * Builds a new immutable {@link Artifact} from the current builder state.
         *
         * @return a new Artifact instance
         * @throws IllegalArgumentException if required fields are missing or parts is empty
         */
        public Artifact build() {
            return new Artifact(Assert.checkNotNullParam("artifactId", artifactId), name, description, Assert.checkNotNullParam("parts", parts), metadata, extensions);
        }
    }
}
