// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

/**
 * <pre>
 * --8&lt;-- [start:AgentCapabilities]
 * Defines optional capabilities supported by an agent.
 * </pre>
 *
 * Protobuf type {@code a2a.v1.AgentCapabilities}
 */
@com.google.protobuf.Generated
public final class AgentCapabilities extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.AgentCapabilities)
    AgentCapabilitiesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AgentCapabilities");
  }
  // Use AgentCapabilities.newBuilder() to construct.
  private AgentCapabilities(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AgentCapabilities() {
    extensions_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_AgentCapabilities_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_AgentCapabilities_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.AgentCapabilities.class, io.a2a.grpc.AgentCapabilities.Builder.class);
  }

  private int bitField0_;
  public static final int STREAMING_FIELD_NUMBER = 1;
  private boolean streaming_ = false;
  /**
   * <pre>
   * Indicates if the agent supports streaming responses.
   * </pre>
   *
   * <code>optional bool streaming = 1;</code>
   * @return Whether the streaming field is set.
   */
  @java.lang.Override
  public boolean hasStreaming() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Indicates if the agent supports streaming responses.
   * </pre>
   *
   * <code>optional bool streaming = 1;</code>
   * @return The streaming.
   */
  @java.lang.Override
  public boolean getStreaming() {
    return streaming_;
  }

  public static final int PUSH_NOTIFICATIONS_FIELD_NUMBER = 2;
  private boolean pushNotifications_ = false;
  /**
   * <pre>
   * Indicates if the agent supports sending push notifications for asynchronous task updates.
   * </pre>
   *
   * <code>optional bool push_notifications = 2;</code>
   * @return Whether the pushNotifications field is set.
   */
  @java.lang.Override
  public boolean hasPushNotifications() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Indicates if the agent supports sending push notifications for asynchronous task updates.
   * </pre>
   *
   * <code>optional bool push_notifications = 2;</code>
   * @return The pushNotifications.
   */
  @java.lang.Override
  public boolean getPushNotifications() {
    return pushNotifications_;
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<io.a2a.grpc.AgentExtension> extensions_;
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.a2a.grpc.AgentExtension> getExtensionsList() {
    return extensions_;
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.a2a.grpc.AgentExtensionOrBuilder> 
      getExtensionsOrBuilderList() {
    return extensions_;
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public int getExtensionsCount() {
    return extensions_.size();
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public io.a2a.grpc.AgentExtension getExtensions(int index) {
    return extensions_.get(index);
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public io.a2a.grpc.AgentExtensionOrBuilder getExtensionsOrBuilder(
      int index) {
    return extensions_.get(index);
  }

  public static final int EXTENDED_AGENT_CARD_FIELD_NUMBER = 5;
  private boolean extendedAgentCard_ = false;
  /**
   * <pre>
   * Indicates if the agent supports providing an extended agent card when authenticated.
   * </pre>
   *
   * <code>optional bool extended_agent_card = 5;</code>
   * @return Whether the extendedAgentCard field is set.
   */
  @java.lang.Override
  public boolean hasExtendedAgentCard() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Indicates if the agent supports providing an extended agent card when authenticated.
   * </pre>
   *
   * <code>optional bool extended_agent_card = 5;</code>
   * @return The extendedAgentCard.
   */
  @java.lang.Override
  public boolean getExtendedAgentCard() {
    return extendedAgentCard_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, streaming_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, pushNotifications_);
    }
    for (int i = 0; i < extensions_.size(); i++) {
      output.writeMessage(3, extensions_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(5, extendedAgentCard_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, streaming_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, pushNotifications_);
    }
    for (int i = 0; i < extensions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, extensions_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, extendedAgentCard_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.AgentCapabilities)) {
      return super.equals(obj);
    }
    io.a2a.grpc.AgentCapabilities other = (io.a2a.grpc.AgentCapabilities) obj;

    if (hasStreaming() != other.hasStreaming()) return false;
    if (hasStreaming()) {
      if (getStreaming()
          != other.getStreaming()) return false;
    }
    if (hasPushNotifications() != other.hasPushNotifications()) return false;
    if (hasPushNotifications()) {
      if (getPushNotifications()
          != other.getPushNotifications()) return false;
    }
    if (!getExtensionsList()
        .equals(other.getExtensionsList())) return false;
    if (hasExtendedAgentCard() != other.hasExtendedAgentCard()) return false;
    if (hasExtendedAgentCard()) {
      if (getExtendedAgentCard()
          != other.getExtendedAgentCard()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStreaming()) {
      hash = (37 * hash) + STREAMING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStreaming());
    }
    if (hasPushNotifications()) {
      hash = (37 * hash) + PUSH_NOTIFICATIONS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPushNotifications());
    }
    if (getExtensionsCount() > 0) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensionsList().hashCode();
    }
    if (hasExtendedAgentCard()) {
      hash = (37 * hash) + EXTENDED_AGENT_CARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExtendedAgentCard());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.AgentCapabilities parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.AgentCapabilities parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.AgentCapabilities parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.AgentCapabilities prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:AgentCapabilities]
   * Defines optional capabilities supported by an agent.
   * </pre>
   *
   * Protobuf type {@code a2a.v1.AgentCapabilities}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.AgentCapabilities)
      io.a2a.grpc.AgentCapabilitiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_AgentCapabilities_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_AgentCapabilities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.AgentCapabilities.class, io.a2a.grpc.AgentCapabilities.Builder.class);
    }

    // Construct using io.a2a.grpc.AgentCapabilities.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      streaming_ = false;
      pushNotifications_ = false;
      if (extensionsBuilder_ == null) {
        extensions_ = java.util.Collections.emptyList();
      } else {
        extensions_ = null;
        extensionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      extendedAgentCard_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_AgentCapabilities_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.AgentCapabilities getDefaultInstanceForType() {
      return io.a2a.grpc.AgentCapabilities.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.AgentCapabilities build() {
      io.a2a.grpc.AgentCapabilities result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.AgentCapabilities buildPartial() {
      io.a2a.grpc.AgentCapabilities result = new io.a2a.grpc.AgentCapabilities(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.a2a.grpc.AgentCapabilities result) {
      if (extensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          extensions_ = java.util.Collections.unmodifiableList(extensions_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.extensions_ = extensions_;
      } else {
        result.extensions_ = extensionsBuilder_.build();
      }
    }

    private void buildPartial0(io.a2a.grpc.AgentCapabilities result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.streaming_ = streaming_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pushNotifications_ = pushNotifications_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.extendedAgentCard_ = extendedAgentCard_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.AgentCapabilities) {
        return mergeFrom((io.a2a.grpc.AgentCapabilities)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.AgentCapabilities other) {
      if (other == io.a2a.grpc.AgentCapabilities.getDefaultInstance()) return this;
      if (other.hasStreaming()) {
        setStreaming(other.getStreaming());
      }
      if (other.hasPushNotifications()) {
        setPushNotifications(other.getPushNotifications());
      }
      if (extensionsBuilder_ == null) {
        if (!other.extensions_.isEmpty()) {
          if (extensions_.isEmpty()) {
            extensions_ = other.extensions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureExtensionsIsMutable();
            extensions_.addAll(other.extensions_);
          }
          onChanged();
        }
      } else {
        if (!other.extensions_.isEmpty()) {
          if (extensionsBuilder_.isEmpty()) {
            extensionsBuilder_.dispose();
            extensionsBuilder_ = null;
            extensions_ = other.extensions_;
            bitField0_ = (bitField0_ & ~0x00000004);
            extensionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetExtensionsFieldBuilder() : null;
          } else {
            extensionsBuilder_.addAllMessages(other.extensions_);
          }
        }
      }
      if (other.hasExtendedAgentCard()) {
        setExtendedAgentCard(other.getExtendedAgentCard());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              streaming_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              pushNotifications_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              io.a2a.grpc.AgentExtension m =
                  input.readMessage(
                      io.a2a.grpc.AgentExtension.parser(),
                      extensionRegistry);
              if (extensionsBuilder_ == null) {
                ensureExtensionsIsMutable();
                extensions_.add(m);
              } else {
                extensionsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 40: {
              extendedAgentCard_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean streaming_ ;
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>optional bool streaming = 1;</code>
     * @return Whether the streaming field is set.
     */
    @java.lang.Override
    public boolean hasStreaming() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>optional bool streaming = 1;</code>
     * @return The streaming.
     */
    @java.lang.Override
    public boolean getStreaming() {
      return streaming_;
    }
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>optional bool streaming = 1;</code>
     * @param value The streaming to set.
     * @return This builder for chaining.
     */
    public Builder setStreaming(boolean value) {

      streaming_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>optional bool streaming = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreaming() {
      bitField0_ = (bitField0_ & ~0x00000001);
      streaming_ = false;
      onChanged();
      return this;
    }

    private boolean pushNotifications_ ;
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>optional bool push_notifications = 2;</code>
     * @return Whether the pushNotifications field is set.
     */
    @java.lang.Override
    public boolean hasPushNotifications() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>optional bool push_notifications = 2;</code>
     * @return The pushNotifications.
     */
    @java.lang.Override
    public boolean getPushNotifications() {
      return pushNotifications_;
    }
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>optional bool push_notifications = 2;</code>
     * @param value The pushNotifications to set.
     * @return This builder for chaining.
     */
    public Builder setPushNotifications(boolean value) {

      pushNotifications_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>optional bool push_notifications = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPushNotifications() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pushNotifications_ = false;
      onChanged();
      return this;
    }

    private java.util.List<io.a2a.grpc.AgentExtension> extensions_ =
      java.util.Collections.emptyList();
    private void ensureExtensionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        extensions_ = new java.util.ArrayList<io.a2a.grpc.AgentExtension>(extensions_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.a2a.grpc.AgentExtension, io.a2a.grpc.AgentExtension.Builder, io.a2a.grpc.AgentExtensionOrBuilder> extensionsBuilder_;

    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public java.util.List<io.a2a.grpc.AgentExtension> getExtensionsList() {
      if (extensionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extensions_);
      } else {
        return extensionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public int getExtensionsCount() {
      if (extensionsBuilder_ == null) {
        return extensions_.size();
      } else {
        return extensionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public io.a2a.grpc.AgentExtension getExtensions(int index) {
      if (extensionsBuilder_ == null) {
        return extensions_.get(index);
      } else {
        return extensionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder setExtensions(
        int index, io.a2a.grpc.AgentExtension value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionsIsMutable();
        extensions_.set(index, value);
        onChanged();
      } else {
        extensionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder setExtensions(
        int index, io.a2a.grpc.AgentExtension.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.set(index, builderForValue.build());
        onChanged();
      } else {
        extensionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(io.a2a.grpc.AgentExtension value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionsIsMutable();
        extensions_.add(value);
        onChanged();
      } else {
        extensionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(
        int index, io.a2a.grpc.AgentExtension value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionsIsMutable();
        extensions_.add(index, value);
        onChanged();
      } else {
        extensionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(
        io.a2a.grpc.AgentExtension.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.add(builderForValue.build());
        onChanged();
      } else {
        extensionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(
        int index, io.a2a.grpc.AgentExtension.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.add(index, builderForValue.build());
        onChanged();
      } else {
        extensionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addAllExtensions(
        java.lang.Iterable<? extends io.a2a.grpc.AgentExtension> values) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extensions_);
        onChanged();
      } else {
        extensionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder clearExtensions() {
      if (extensionsBuilder_ == null) {
        extensions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        extensionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder removeExtensions(int index) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.remove(index);
        onChanged();
      } else {
        extensionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public io.a2a.grpc.AgentExtension.Builder getExtensionsBuilder(
        int index) {
      return internalGetExtensionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public io.a2a.grpc.AgentExtensionOrBuilder getExtensionsOrBuilder(
        int index) {
      if (extensionsBuilder_ == null) {
        return extensions_.get(index);  } else {
        return extensionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public java.util.List<? extends io.a2a.grpc.AgentExtensionOrBuilder> 
         getExtensionsOrBuilderList() {
      if (extensionsBuilder_ != null) {
        return extensionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extensions_);
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public io.a2a.grpc.AgentExtension.Builder addExtensionsBuilder() {
      return internalGetExtensionsFieldBuilder().addBuilder(
          io.a2a.grpc.AgentExtension.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public io.a2a.grpc.AgentExtension.Builder addExtensionsBuilder(
        int index) {
      return internalGetExtensionsFieldBuilder().addBuilder(
          index, io.a2a.grpc.AgentExtension.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
     */
    public java.util.List<io.a2a.grpc.AgentExtension.Builder> 
         getExtensionsBuilderList() {
      return internalGetExtensionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.a2a.grpc.AgentExtension, io.a2a.grpc.AgentExtension.Builder, io.a2a.grpc.AgentExtensionOrBuilder> 
        internalGetExtensionsFieldBuilder() {
      if (extensionsBuilder_ == null) {
        extensionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.a2a.grpc.AgentExtension, io.a2a.grpc.AgentExtension.Builder, io.a2a.grpc.AgentExtensionOrBuilder>(
                extensions_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        extensions_ = null;
      }
      return extensionsBuilder_;
    }

    private boolean extendedAgentCard_ ;
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>optional bool extended_agent_card = 5;</code>
     * @return Whether the extendedAgentCard field is set.
     */
    @java.lang.Override
    public boolean hasExtendedAgentCard() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>optional bool extended_agent_card = 5;</code>
     * @return The extendedAgentCard.
     */
    @java.lang.Override
    public boolean getExtendedAgentCard() {
      return extendedAgentCard_;
    }
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>optional bool extended_agent_card = 5;</code>
     * @param value The extendedAgentCard to set.
     * @return This builder for chaining.
     */
    public Builder setExtendedAgentCard(boolean value) {

      extendedAgentCard_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>optional bool extended_agent_card = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtendedAgentCard() {
      bitField0_ = (bitField0_ & ~0x00000008);
      extendedAgentCard_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.AgentCapabilities)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.AgentCapabilities)
  private static final io.a2a.grpc.AgentCapabilities DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.AgentCapabilities();
  }

  public static io.a2a.grpc.AgentCapabilities getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentCapabilities>
      PARSER = new com.google.protobuf.AbstractParser<AgentCapabilities>() {
    @java.lang.Override
    public AgentCapabilities parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AgentCapabilities> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentCapabilities> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.AgentCapabilities getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

