// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface AgentCapabilitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentCapabilities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indicates if the agent supports streaming responses.
   * </pre>
   *
   * <code>optional bool streaming = 1;</code>
   * @return Whether the streaming field is set.
   */
  boolean hasStreaming();
  /**
   * <pre>
   * Indicates if the agent supports streaming responses.
   * </pre>
   *
   * <code>optional bool streaming = 1;</code>
   * @return The streaming.
   */
  boolean getStreaming();

  /**
   * <pre>
   * Indicates if the agent supports sending push notifications for asynchronous task updates.
   * </pre>
   *
   * <code>optional bool push_notifications = 2;</code>
   * @return Whether the pushNotifications field is set.
   */
  boolean hasPushNotifications();
  /**
   * <pre>
   * Indicates if the agent supports sending push notifications for asynchronous task updates.
   * </pre>
   *
   * <code>optional bool push_notifications = 2;</code>
   * @return The pushNotifications.
   */
  boolean getPushNotifications();

  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  java.util.List<io.a2a.grpc.AgentExtension> 
      getExtensionsList();
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  io.a2a.grpc.AgentExtension getExtensions(int index);
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  int getExtensionsCount();
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  java.util.List<? extends io.a2a.grpc.AgentExtensionOrBuilder> 
      getExtensionsOrBuilderList();
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .a2a.v1.AgentExtension extensions = 3;</code>
   */
  io.a2a.grpc.AgentExtensionOrBuilder getExtensionsOrBuilder(
      int index);

  /**
   * <pre>
   * Indicates if the agent supports providing an extended agent card when authenticated.
   * </pre>
   *
   * <code>optional bool extended_agent_card = 5;</code>
   * @return Whether the extendedAgentCard field is set.
   */
  boolean hasExtendedAgentCard();
  /**
   * <pre>
   * Indicates if the agent supports providing an extended agent card when authenticated.
   * </pre>
   *
   * <code>optional bool extended_agent_card = 5;</code>
   * @return The extendedAgentCard.
   */
  boolean getExtendedAgentCard();
}
