// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface AgentInterfaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentInterface)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The URL where this interface is available. Must be a valid absolute HTTPS URL in production.
   * Example: "https://api.example.com/a2a/v1", "https://grpc.example.com/a2a"
   * </pre>
   *
   * <code>string url = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * The URL where this interface is available. Must be a valid absolute HTTPS URL in production.
   * Example: "https://api.example.com/a2a/v1", "https://grpc.example.com/a2a"
   * </pre>
   *
   * <code>string url = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * The protocol binding supported at this URL. This is an open form string, to be
   * easily extended for other protocol bindings. The core ones officially
   * supported are `JSONRPC`, `GRPC` and `HTTP+JSON`.
   * </pre>
   *
   * <code>string protocol_binding = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The protocolBinding.
   */
  java.lang.String getProtocolBinding();
  /**
   * <pre>
   * The protocol binding supported at this URL. This is an open form string, to be
   * easily extended for other protocol bindings. The core ones officially
   * supported are `JSONRPC`, `GRPC` and `HTTP+JSON`.
   * </pre>
   *
   * <code>string protocol_binding = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for protocolBinding.
   */
  com.google.protobuf.ByteString
      getProtocolBindingBytes();

  /**
   * <pre>
   * Tenant to be set in the request when calling the agent.
   * </pre>
   *
   * <code>string tenant = 3;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Tenant to be set in the request when calling the agent.
   * </pre>
   *
   * <code>string tenant = 3;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The version of the A2A protocol this interface exposes.
   * Use the latest supported minor version per major version.
   * Examples: "0.3", "1.0"
   * </pre>
   *
   * <code>string protocol_version = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The protocolVersion.
   */
  java.lang.String getProtocolVersion();
  /**
   * <pre>
   * The version of the A2A protocol this interface exposes.
   * Use the latest supported minor version per major version.
   * Examples: "0.3", "1.0"
   * </pre>
   *
   * <code>string protocol_version = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for protocolVersion.
   */
  com.google.protobuf.ByteString
      getProtocolVersionBytes();
}
