// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface AgentSkillOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentSkill)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A unique identifier for the agent's skill.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * A unique identifier for the agent's skill.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * A human-readable name for the skill.
   * </pre>
   *
   * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * A human-readable name for the skill.
   * </pre>
   *
   * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * A detailed description of the skill.
   * </pre>
   *
   * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * A detailed description of the skill.
   * </pre>
   *
   * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @return A list containing the examples.
   */
  java.util.List<java.lang.String>
      getExamplesList();
  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @return The count of examples.
   */
  int getExamplesCount();
  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @param index The index of the element to return.
   * @return The examples at the given index.
   */
  java.lang.String getExamples(int index);
  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the examples at the given index.
   */
  com.google.protobuf.ByteString
      getExamplesBytes(int index);

  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @return A list containing the inputModes.
   */
  java.util.List<java.lang.String>
      getInputModesList();
  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @return The count of inputModes.
   */
  int getInputModesCount();
  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @param index The index of the element to return.
   * @return The inputModes at the given index.
   */
  java.lang.String getInputModes(int index);
  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the inputModes at the given index.
   */
  com.google.protobuf.ByteString
      getInputModesBytes(int index);

  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @return A list containing the outputModes.
   */
  java.util.List<java.lang.String>
      getOutputModesList();
  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @return The count of outputModes.
   */
  int getOutputModesCount();
  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @param index The index of the element to return.
   * @return The outputModes at the given index.
   */
  java.lang.String getOutputModes(int index);
  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputModes at the given index.
   */
  com.google.protobuf.ByteString
      getOutputModesBytes(int index);

  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  java.util.List<io.a2a.grpc.SecurityRequirement> 
      getSecurityRequirementsList();
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  io.a2a.grpc.SecurityRequirement getSecurityRequirements(int index);
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  int getSecurityRequirementsCount();
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  java.util.List<? extends io.a2a.grpc.SecurityRequirementOrBuilder> 
      getSecurityRequirementsOrBuilderList();
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  io.a2a.grpc.SecurityRequirementOrBuilder getSecurityRequirementsOrBuilder(
      int index);
}
