// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

/**
 * <pre>
 * --8&lt;-- [start:PushNotificationAuthenticationInfo]
 * Defines authentication details, used for push notifications.
 * </pre>
 *
 * Protobuf type {@code a2a.v1.AuthenticationInfo}
 */
@com.google.protobuf.Generated
public final class AuthenticationInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.AuthenticationInfo)
    AuthenticationInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AuthenticationInfo");
  }
  // Use AuthenticationInfo.newBuilder() to construct.
  private AuthenticationInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AuthenticationInfo() {
    scheme_ = "";
    credentials_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_AuthenticationInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_AuthenticationInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.AuthenticationInfo.class, io.a2a.grpc.AuthenticationInfo.Builder.class);
  }

  public static final int SCHEME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scheme_ = "";
  /**
   * <pre>
   * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
   * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
   * </pre>
   *
   * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The scheme.
   */
  @java.lang.Override
  public java.lang.String getScheme() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scheme_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
   * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
   * </pre>
   *
   * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for scheme.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemeBytes() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scheme_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREDENTIALS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object credentials_ = "";
  /**
   * <pre>
   * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
   * </pre>
   *
   * <code>string credentials = 2;</code>
   * @return The credentials.
   */
  @java.lang.Override
  public java.lang.String getCredentials() {
    java.lang.Object ref = credentials_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      credentials_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
   * </pre>
   *
   * <code>string credentials = 2;</code>
   * @return The bytes for credentials.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCredentialsBytes() {
    java.lang.Object ref = credentials_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      credentials_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scheme_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, scheme_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(credentials_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, credentials_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scheme_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, scheme_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(credentials_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, credentials_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.AuthenticationInfo)) {
      return super.equals(obj);
    }
    io.a2a.grpc.AuthenticationInfo other = (io.a2a.grpc.AuthenticationInfo) obj;

    if (!getScheme()
        .equals(other.getScheme())) return false;
    if (!getCredentials()
        .equals(other.getCredentials())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEME_FIELD_NUMBER;
    hash = (53 * hash) + getScheme().hashCode();
    hash = (37 * hash) + CREDENTIALS_FIELD_NUMBER;
    hash = (53 * hash) + getCredentials().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.AuthenticationInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.AuthenticationInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.AuthenticationInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.AuthenticationInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:PushNotificationAuthenticationInfo]
   * Defines authentication details, used for push notifications.
   * </pre>
   *
   * Protobuf type {@code a2a.v1.AuthenticationInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.AuthenticationInfo)
      io.a2a.grpc.AuthenticationInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_AuthenticationInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_AuthenticationInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.AuthenticationInfo.class, io.a2a.grpc.AuthenticationInfo.Builder.class);
    }

    // Construct using io.a2a.grpc.AuthenticationInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scheme_ = "";
      credentials_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_AuthenticationInfo_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.AuthenticationInfo getDefaultInstanceForType() {
      return io.a2a.grpc.AuthenticationInfo.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.AuthenticationInfo build() {
      io.a2a.grpc.AuthenticationInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.AuthenticationInfo buildPartial() {
      io.a2a.grpc.AuthenticationInfo result = new io.a2a.grpc.AuthenticationInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.AuthenticationInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scheme_ = scheme_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.credentials_ = credentials_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.AuthenticationInfo) {
        return mergeFrom((io.a2a.grpc.AuthenticationInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.AuthenticationInfo other) {
      if (other == io.a2a.grpc.AuthenticationInfo.getDefaultInstance()) return this;
      if (!other.getScheme().isEmpty()) {
        scheme_ = other.scheme_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCredentials().isEmpty()) {
        credentials_ = other.credentials_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              scheme_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              credentials_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object scheme_ = "";
    /**
     * <pre>
     * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
     * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
     * </pre>
     *
     * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The scheme.
     */
    public java.lang.String getScheme() {
      java.lang.Object ref = scheme_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheme_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
     * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
     * </pre>
     *
     * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for scheme.
     */
    public com.google.protobuf.ByteString
        getSchemeBytes() {
      java.lang.Object ref = scheme_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheme_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
     * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
     * </pre>
     *
     * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The scheme to set.
     * @return This builder for chaining.
     */
    public Builder setScheme(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scheme_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
     * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
     * </pre>
     *
     * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearScheme() {
      scheme_ = getDefaultInstance().getScheme();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
     * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
     * </pre>
     *
     * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for scheme to set.
     * @return This builder for chaining.
     */
    public Builder setSchemeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scheme_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object credentials_ = "";
    /**
     * <pre>
     * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
     * </pre>
     *
     * <code>string credentials = 2;</code>
     * @return The credentials.
     */
    public java.lang.String getCredentials() {
      java.lang.Object ref = credentials_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        credentials_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
     * </pre>
     *
     * <code>string credentials = 2;</code>
     * @return The bytes for credentials.
     */
    public com.google.protobuf.ByteString
        getCredentialsBytes() {
      java.lang.Object ref = credentials_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        credentials_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
     * </pre>
     *
     * <code>string credentials = 2;</code>
     * @param value The credentials to set.
     * @return This builder for chaining.
     */
    public Builder setCredentials(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      credentials_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
     * </pre>
     *
     * <code>string credentials = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredentials() {
      credentials_ = getDefaultInstance().getCredentials();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
     * </pre>
     *
     * <code>string credentials = 2;</code>
     * @param value The bytes for credentials to set.
     * @return This builder for chaining.
     */
    public Builder setCredentialsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      credentials_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.AuthenticationInfo)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.AuthenticationInfo)
  private static final io.a2a.grpc.AuthenticationInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.AuthenticationInfo();
  }

  public static io.a2a.grpc.AuthenticationInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthenticationInfo>
      PARSER = new com.google.protobuf.AbstractParser<AuthenticationInfo>() {
    @java.lang.Override
    public AuthenticationInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthenticationInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthenticationInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.AuthenticationInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

