// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface AuthenticationInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AuthenticationInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
   * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
   * </pre>
   *
   * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The scheme.
   */
  java.lang.String getScheme();
  /**
   * <pre>
   * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
   * Common values: `Bearer`, `Basic`, `Digest`. Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
   * </pre>
   *
   * <code>string scheme = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for scheme.
   */
  com.google.protobuf.ByteString
      getSchemeBytes();

  /**
   * <pre>
   * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
   * </pre>
   *
   * <code>string credentials = 2;</code>
   * @return The credentials.
   */
  java.lang.String getCredentials();
  /**
   * <pre>
   * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
   * </pre>
   *
   * <code>string credentials = 2;</code>
   * @return The bytes for credentials.
   */
  com.google.protobuf.ByteString
      getCredentialsBytes();
}
