// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

/**
 * <pre>
 * --8&lt;-- [start:Part]
 * Part represents a container for a section of communication content.
 * Parts can be purely textual, some sort of file (image, video, etc) or
 * a structured data blob (i.e. JSON).
 * </pre>
 *
 * Protobuf type {@code a2a.v1.Part}
 */
@com.google.protobuf.Generated
public final class Part extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.Part)
    PartOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Part");
  }
  // Use Part.newBuilder() to construct.
  private Part(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Part() {
    filename_ = "";
    mediaType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_Part_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_Part_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.Part.class, io.a2a.grpc.Part.Builder.class);
  }

  private int bitField0_;
  private int contentCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object content_;
  public enum ContentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TEXT(1),
    RAW(2),
    URL(3),
    DATA(4),
    CONTENT_NOT_SET(0);
    private final int value;
    private ContentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContentCase forNumber(int value) {
      switch (value) {
        case 1: return TEXT;
        case 2: return RAW;
        case 3: return URL;
        case 4: return DATA;
        case 0: return CONTENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ContentCase
  getContentCase() {
    return ContentCase.forNumber(
        contentCase_);
  }

  public static final int TEXT_FIELD_NUMBER = 1;
  /**
   * <pre>
   * The string content of the text part.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return Whether the text field is set.
   */
  public boolean hasText() {
    return contentCase_ == 1;
  }
  /**
   * <pre>
   * The string content of the text part.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The text.
   */
  public java.lang.String getText() {
    java.lang.Object ref = "";
    if (contentCase_ == 1) {
      ref = content_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (contentCase_ == 1) {
        content_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The string content of the text part.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = "";
    if (contentCase_ == 1) {
      ref = content_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (contentCase_ == 1) {
        content_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RAW_FIELD_NUMBER = 2;
  /**
   * <pre>
   * The raw byte content of a file. In JSON serialization, this is encoded as a base64 string.
   * </pre>
   *
   * <code>bytes raw = 2;</code>
   * @return Whether the raw field is set.
   */
  @java.lang.Override
  public boolean hasRaw() {
    return contentCase_ == 2;
  }
  /**
   * <pre>
   * The raw byte content of a file. In JSON serialization, this is encoded as a base64 string.
   * </pre>
   *
   * <code>bytes raw = 2;</code>
   * @return The raw.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRaw() {
    if (contentCase_ == 2) {
      return (com.google.protobuf.ByteString) content_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int URL_FIELD_NUMBER = 3;
  /**
   * <pre>
   * A URL pointing to the file's content.
   * </pre>
   *
   * <code>string url = 3;</code>
   * @return Whether the url field is set.
   */
  public boolean hasUrl() {
    return contentCase_ == 3;
  }
  /**
   * <pre>
   * A URL pointing to the file's content.
   * </pre>
   *
   * <code>string url = 3;</code>
   * @return The url.
   */
  public java.lang.String getUrl() {
    java.lang.Object ref = "";
    if (contentCase_ == 3) {
      ref = content_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (contentCase_ == 3) {
        content_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * A URL pointing to the file's content.
   * </pre>
   *
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = "";
    if (contentCase_ == 3) {
      ref = content_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (contentCase_ == 3) {
        content_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
   * </pre>
   *
   * <code>.google.protobuf.Value data = 4;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return contentCase_ == 4;
  }
  /**
   * <pre>
   * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
   * </pre>
   *
   * <code>.google.protobuf.Value data = 4;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.Value getData() {
    if (contentCase_ == 4) {
       return (com.google.protobuf.Value) content_;
    }
    return com.google.protobuf.Value.getDefaultInstance();
  }
  /**
   * <pre>
   * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
   * </pre>
   *
   * <code>.google.protobuf.Value data = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ValueOrBuilder getDataOrBuilder() {
    if (contentCase_ == 4) {
       return (com.google.protobuf.Value) content_;
    }
    return com.google.protobuf.Value.getDefaultInstance();
  }

  public static final int METADATA_FIELD_NUMBER = 5;
  private com.google.protobuf.Struct metadata_;
  /**
   * <pre>
   * Optional metadata associated with this part.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 5;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional metadata associated with this part.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 5;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetadata() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * Optional metadata associated with this part.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }

  public static final int FILENAME_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object filename_ = "";
  /**
   * <pre>
   * An optional name for the file (e.g., "document.pdf").
   * </pre>
   *
   * <code>string filename = 6;</code>
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * An optional name for the file (e.g., "document.pdf").
   * </pre>
   *
   * <code>string filename = 6;</code>
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIA_TYPE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mediaType_ = "";
  /**
   * <pre>
   * The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
   * This field is available for all part types.
   * </pre>
   *
   * <code>string media_type = 7;</code>
   * @return The mediaType.
   */
  @java.lang.Override
  public java.lang.String getMediaType() {
    java.lang.Object ref = mediaType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
   * This field is available for all part types.
   * </pre>
   *
   * <code>string media_type = 7;</code>
   * @return The bytes for mediaType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMediaTypeBytes() {
    java.lang.Object ref = mediaType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (contentCase_ == 1) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, content_);
    }
    if (contentCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) content_);
    }
    if (contentCase_ == 3) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, content_);
    }
    if (contentCase_ == 4) {
      output.writeMessage(4, (com.google.protobuf.Value) content_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getMetadata());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filename_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, filename_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mediaType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, mediaType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (contentCase_ == 1) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, content_);
    }
    if (contentCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) content_);
    }
    if (contentCase_ == 3) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, content_);
    }
    if (contentCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.google.protobuf.Value) content_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getMetadata());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filename_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, filename_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mediaType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, mediaType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.Part)) {
      return super.equals(obj);
    }
    io.a2a.grpc.Part other = (io.a2a.grpc.Part) obj;

    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (!getMediaType()
        .equals(other.getMediaType())) return false;
    if (!getContentCase().equals(other.getContentCase())) return false;
    switch (contentCase_) {
      case 1:
        if (!getText()
            .equals(other.getText())) return false;
        break;
      case 2:
        if (!getRaw()
            .equals(other.getRaw())) return false;
        break;
      case 3:
        if (!getUrl()
            .equals(other.getUrl())) return false;
        break;
      case 4:
        if (!getData()
            .equals(other.getData())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (37 * hash) + MEDIA_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMediaType().hashCode();
    switch (contentCase_) {
      case 1:
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        break;
      case 2:
        hash = (37 * hash) + RAW_FIELD_NUMBER;
        hash = (53 * hash) + getRaw().hashCode();
        break;
      case 3:
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
        break;
      case 4:
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.Part parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.Part parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.Part parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.Part parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.Part parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.Part parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.Part parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.Part parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.Part parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.Part parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.Part parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.Part parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.Part prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:Part]
   * Part represents a container for a section of communication content.
   * Parts can be purely textual, some sort of file (image, video, etc) or
   * a structured data blob (i.e. JSON).
   * </pre>
   *
   * Protobuf type {@code a2a.v1.Part}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.Part)
      io.a2a.grpc.PartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_Part_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_Part_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.Part.class, io.a2a.grpc.Part.Builder.class);
    }

    // Construct using io.a2a.grpc.Part.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (dataBuilder_ != null) {
        dataBuilder_.clear();
      }
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      filename_ = "";
      mediaType_ = "";
      contentCase_ = 0;
      content_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_Part_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.Part getDefaultInstanceForType() {
      return io.a2a.grpc.Part.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.Part build() {
      io.a2a.grpc.Part result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.Part buildPartial() {
      io.a2a.grpc.Part result = new io.a2a.grpc.Part(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.Part result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.filename_ = filename_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.mediaType_ = mediaType_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(io.a2a.grpc.Part result) {
      result.contentCase_ = contentCase_;
      result.content_ = this.content_;
      if (contentCase_ == 4 &&
          dataBuilder_ != null) {
        result.content_ = dataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.Part) {
        return mergeFrom((io.a2a.grpc.Part)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.Part other) {
      if (other == io.a2a.grpc.Part.getDefaultInstance()) return this;
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getMediaType().isEmpty()) {
        mediaType_ = other.mediaType_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      switch (other.getContentCase()) {
        case TEXT: {
          contentCase_ = 1;
          content_ = other.content_;
          onChanged();
          break;
        }
        case RAW: {
          setRaw(other.getRaw());
          break;
        }
        case URL: {
          contentCase_ = 3;
          content_ = other.content_;
          onChanged();
          break;
        }
        case DATA: {
          mergeData(other.getData());
          break;
        }
        case CONTENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              contentCase_ = 1;
              content_ = s;
              break;
            } // case 10
            case 18: {
              content_ = input.readBytes();
              contentCase_ = 2;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              contentCase_ = 3;
              content_ = s;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              filename_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              mediaType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int contentCase_ = 0;
    private java.lang.Object content_;
    public ContentCase
        getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public Builder clearContent() {
      contentCase_ = 0;
      content_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <pre>
     * The string content of the text part.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return contentCase_ == 1;
    }
    /**
     * <pre>
     * The string content of the text part.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = "";
      if (contentCase_ == 1) {
        ref = content_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (contentCase_ == 1) {
          content_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The string content of the text part.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = "";
      if (contentCase_ == 1) {
        ref = content_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (contentCase_ == 1) {
          content_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The string content of the text part.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentCase_ = 1;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The string content of the text part.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      if (contentCase_ == 1) {
        contentCase_ = 0;
        content_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The string content of the text part.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentCase_ = 1;
      content_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * The raw byte content of a file. In JSON serialization, this is encoded as a base64 string.
     * </pre>
     *
     * <code>bytes raw = 2;</code>
     * @return Whether the raw field is set.
     */
    public boolean hasRaw() {
      return contentCase_ == 2;
    }
    /**
     * <pre>
     * The raw byte content of a file. In JSON serialization, this is encoded as a base64 string.
     * </pre>
     *
     * <code>bytes raw = 2;</code>
     * @return The raw.
     */
    public com.google.protobuf.ByteString getRaw() {
      if (contentCase_ == 2) {
        return (com.google.protobuf.ByteString) content_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * The raw byte content of a file. In JSON serialization, this is encoded as a base64 string.
     * </pre>
     *
     * <code>bytes raw = 2;</code>
     * @param value The raw to set.
     * @return This builder for chaining.
     */
    public Builder setRaw(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      contentCase_ = 2;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The raw byte content of a file. In JSON serialization, this is encoded as a base64 string.
     * </pre>
     *
     * <code>bytes raw = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRaw() {
      if (contentCase_ == 2) {
        contentCase_ = 0;
        content_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * A URL pointing to the file's content.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return contentCase_ == 3;
    }
    /**
     * <pre>
     * A URL pointing to the file's content.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = "";
      if (contentCase_ == 3) {
        ref = content_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (contentCase_ == 3) {
          content_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A URL pointing to the file's content.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = "";
      if (contentCase_ == 3) {
        ref = content_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (contentCase_ == 3) {
          content_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A URL pointing to the file's content.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentCase_ = 3;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A URL pointing to the file's content.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      if (contentCase_ == 3) {
        contentCase_ = 0;
        content_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * A URL pointing to the file's content.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentCase_ = 3;
      content_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> dataBuilder_;
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return contentCase_ == 4;
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.Value getData() {
      if (dataBuilder_ == null) {
        if (contentCase_ == 4) {
          return (com.google.protobuf.Value) content_;
        }
        return com.google.protobuf.Value.getDefaultInstance();
      } else {
        if (contentCase_ == 4) {
          return dataBuilder_.getMessage();
        }
        return com.google.protobuf.Value.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     */
    public Builder setData(com.google.protobuf.Value value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }
      contentCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     */
    public Builder setData(
        com.google.protobuf.Value.Builder builderForValue) {
      if (dataBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     */
    public Builder mergeData(com.google.protobuf.Value value) {
      if (dataBuilder_ == null) {
        if (contentCase_ == 4 &&
            content_ != com.google.protobuf.Value.getDefaultInstance()) {
          content_ = com.google.protobuf.Value.newBuilder((com.google.protobuf.Value) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 4) {
          dataBuilder_.mergeFrom(value);
        } else {
          dataBuilder_.setMessage(value);
        }
      }
      contentCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        if (contentCase_ == 4) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 4) {
          contentCase_ = 0;
          content_ = null;
        }
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     */
    public com.google.protobuf.Value.Builder getDataBuilder() {
      return internalGetDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ValueOrBuilder getDataOrBuilder() {
      if ((contentCase_ == 4) && (dataBuilder_ != null)) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 4) {
          return (com.google.protobuf.Value) content_;
        }
        return com.google.protobuf.Value.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
     * </pre>
     *
     * <code>.google.protobuf.Value data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> 
        internalGetDataFieldBuilder() {
      if (dataBuilder_ == null) {
        if (!(contentCase_ == 4)) {
          content_ = com.google.protobuf.Value.getDefaultInstance();
        }
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                (com.google.protobuf.Value) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 4;
      onChanged();
      return dataBuilder_;
    }

    private com.google.protobuf.Struct metadata_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     * @return The metadata.
     */
    public com.google.protobuf.Struct getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     */
    public Builder setMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          metadata_ != null &&
          metadata_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000010);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * Optional metadata associated with this part.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        internalGetMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private java.lang.Object filename_ = "";
    /**
     * <pre>
     * An optional name for the file (e.g., "document.pdf").
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * An optional name for the file (e.g., "document.pdf").
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * An optional name for the file (e.g., "document.pdf").
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      filename_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An optional name for the file (e.g., "document.pdf").
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      filename_ = getDefaultInstance().getFilename();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An optional name for the file (e.g., "document.pdf").
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      filename_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object mediaType_ = "";
    /**
     * <pre>
     * The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
     * This field is available for all part types.
     * </pre>
     *
     * <code>string media_type = 7;</code>
     * @return The mediaType.
     */
    public java.lang.String getMediaType() {
      java.lang.Object ref = mediaType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
     * This field is available for all part types.
     * </pre>
     *
     * <code>string media_type = 7;</code>
     * @return The bytes for mediaType.
     */
    public com.google.protobuf.ByteString
        getMediaTypeBytes() {
      java.lang.Object ref = mediaType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
     * This field is available for all part types.
     * </pre>
     *
     * <code>string media_type = 7;</code>
     * @param value The mediaType to set.
     * @return This builder for chaining.
     */
    public Builder setMediaType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mediaType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
     * This field is available for all part types.
     * </pre>
     *
     * <code>string media_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaType() {
      mediaType_ = getDefaultInstance().getMediaType();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
     * This field is available for all part types.
     * </pre>
     *
     * <code>string media_type = 7;</code>
     * @param value The bytes for mediaType to set.
     * @return This builder for chaining.
     */
    public Builder setMediaTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mediaType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.Part)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.Part)
  private static final io.a2a.grpc.Part DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.Part();
  }

  public static io.a2a.grpc.Part getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Part>
      PARSER = new com.google.protobuf.AbstractParser<Part>() {
    @java.lang.Override
    public Part parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Part> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Part> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.Part getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

