// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface PushNotificationConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.PushNotificationConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A unique identifier (e.g. UUID) for this push notification.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * A unique identifier (e.g. UUID) for this push notification.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Url to send the notification too
   * </pre>
   *
   * <code>string url = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * Url to send the notification too
   * </pre>
   *
   * <code>string url = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * Token unique for this task/session
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * Token unique for this task/session
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   * Authentication information required to send the notification
   * </pre>
   *
   * <code>.a2a.v1.AuthenticationInfo authentication = 4;</code>
   * @return Whether the authentication field is set.
   */
  boolean hasAuthentication();
  /**
   * <pre>
   * Authentication information required to send the notification
   * </pre>
   *
   * <code>.a2a.v1.AuthenticationInfo authentication = 4;</code>
   * @return The authentication.
   */
  io.a2a.grpc.AuthenticationInfo getAuthentication();
  /**
   * <pre>
   * Authentication information required to send the notification
   * </pre>
   *
   * <code>.a2a.v1.AuthenticationInfo authentication = 4;</code>
   */
  io.a2a.grpc.AuthenticationInfoOrBuilder getAuthenticationOrBuilder();
}
