// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SecurityRequirementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SecurityRequirement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  int getSchemesCount();
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  boolean containsSchemes(
      java.lang.String key);
  /**
   * Use {@link #getSchemesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.a2a.grpc.StringList>
  getSchemes();
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  java.util.Map<java.lang.String, io.a2a.grpc.StringList>
  getSchemesMap();
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  /* nullable */
io.a2a.grpc.StringList getSchemesOrDefault(
      java.lang.String key,
      /* nullable */
io.a2a.grpc.StringList defaultValue);
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  io.a2a.grpc.StringList getSchemesOrThrow(
      java.lang.String key);
}
