// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

/**
 * <pre>
 * --8&lt;-- [start:SendMessageConfiguration]
 * Configuration of a send message request.
 * </pre>
 *
 * Protobuf type {@code a2a.v1.SendMessageConfiguration}
 */
@com.google.protobuf.Generated
public final class SendMessageConfiguration extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.SendMessageConfiguration)
    SendMessageConfigurationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "SendMessageConfiguration");
  }
  // Use SendMessageConfiguration.newBuilder() to construct.
  private SendMessageConfiguration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SendMessageConfiguration() {
    acceptedOutputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_SendMessageConfiguration_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_SendMessageConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.SendMessageConfiguration.class, io.a2a.grpc.SendMessageConfiguration.Builder.class);
  }

  private int bitField0_;
  public static final int ACCEPTED_OUTPUT_MODES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList acceptedOutputModes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @return A list containing the acceptedOutputModes.
   */
  public com.google.protobuf.ProtocolStringList
      getAcceptedOutputModesList() {
    return acceptedOutputModes_;
  }
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @return The count of acceptedOutputModes.
   */
  public int getAcceptedOutputModesCount() {
    return acceptedOutputModes_.size();
  }
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @param index The index of the element to return.
   * @return The acceptedOutputModes at the given index.
   */
  public java.lang.String getAcceptedOutputModes(int index) {
    return acceptedOutputModes_.get(index);
  }
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the acceptedOutputModes at the given index.
   */
  public com.google.protobuf.ByteString
      getAcceptedOutputModesBytes(int index) {
    return acceptedOutputModes_.getByteString(index);
  }

  public static final int PUSH_NOTIFICATION_CONFIG_FIELD_NUMBER = 2;
  private io.a2a.grpc.PushNotificationConfig pushNotificationConfig_;
  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * </pre>
   *
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
   * @return Whether the pushNotificationConfig field is set.
   */
  @java.lang.Override
  public boolean hasPushNotificationConfig() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * </pre>
   *
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
   * @return The pushNotificationConfig.
   */
  @java.lang.Override
  public io.a2a.grpc.PushNotificationConfig getPushNotificationConfig() {
    return pushNotificationConfig_ == null ? io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
  }
  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * </pre>
   *
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
   */
  @java.lang.Override
  public io.a2a.grpc.PushNotificationConfigOrBuilder getPushNotificationConfigOrBuilder() {
    return pushNotificationConfig_ == null ? io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
  }

  public static final int HISTORY_LENGTH_FIELD_NUMBER = 3;
  private int historyLength_ = 0;
  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return Whether the historyLength field is set.
   */
  @java.lang.Override
  public boolean hasHistoryLength() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return The historyLength.
   */
  @java.lang.Override
  public int getHistoryLength() {
    return historyLength_;
  }

  public static final int BLOCKING_FIELD_NUMBER = 4;
  private boolean blocking_ = false;
  /**
   * <pre>
   * If true, the operation waits until the task reaches a terminal or interrupted state before returning. Default is false.
   * </pre>
   *
   * <code>bool blocking = 4;</code>
   * @return The blocking.
   */
  @java.lang.Override
  public boolean getBlocking() {
    return blocking_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < acceptedOutputModes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, acceptedOutputModes_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPushNotificationConfig());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(3, historyLength_);
    }
    if (blocking_ != false) {
      output.writeBool(4, blocking_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < acceptedOutputModes_.size(); i++) {
        dataSize += computeStringSizeNoTag(acceptedOutputModes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAcceptedOutputModesList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPushNotificationConfig());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, historyLength_);
    }
    if (blocking_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, blocking_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.SendMessageConfiguration)) {
      return super.equals(obj);
    }
    io.a2a.grpc.SendMessageConfiguration other = (io.a2a.grpc.SendMessageConfiguration) obj;

    if (!getAcceptedOutputModesList()
        .equals(other.getAcceptedOutputModesList())) return false;
    if (hasPushNotificationConfig() != other.hasPushNotificationConfig()) return false;
    if (hasPushNotificationConfig()) {
      if (!getPushNotificationConfig()
          .equals(other.getPushNotificationConfig())) return false;
    }
    if (hasHistoryLength() != other.hasHistoryLength()) return false;
    if (hasHistoryLength()) {
      if (getHistoryLength()
          != other.getHistoryLength()) return false;
    }
    if (getBlocking()
        != other.getBlocking()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAcceptedOutputModesCount() > 0) {
      hash = (37 * hash) + ACCEPTED_OUTPUT_MODES_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptedOutputModesList().hashCode();
    }
    if (hasPushNotificationConfig()) {
      hash = (37 * hash) + PUSH_NOTIFICATION_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getPushNotificationConfig().hashCode();
    }
    if (hasHistoryLength()) {
      hash = (37 * hash) + HISTORY_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getHistoryLength();
    }
    hash = (37 * hash) + BLOCKING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBlocking());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.SendMessageConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.SendMessageConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.SendMessageConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.SendMessageConfiguration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:SendMessageConfiguration]
   * Configuration of a send message request.
   * </pre>
   *
   * Protobuf type {@code a2a.v1.SendMessageConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.SendMessageConfiguration)
      io.a2a.grpc.SendMessageConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_SendMessageConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_SendMessageConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.SendMessageConfiguration.class, io.a2a.grpc.SendMessageConfiguration.Builder.class);
    }

    // Construct using io.a2a.grpc.SendMessageConfiguration.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPushNotificationConfigFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      acceptedOutputModes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      pushNotificationConfig_ = null;
      if (pushNotificationConfigBuilder_ != null) {
        pushNotificationConfigBuilder_.dispose();
        pushNotificationConfigBuilder_ = null;
      }
      historyLength_ = 0;
      blocking_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_SendMessageConfiguration_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.SendMessageConfiguration getDefaultInstanceForType() {
      return io.a2a.grpc.SendMessageConfiguration.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.SendMessageConfiguration build() {
      io.a2a.grpc.SendMessageConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.SendMessageConfiguration buildPartial() {
      io.a2a.grpc.SendMessageConfiguration result = new io.a2a.grpc.SendMessageConfiguration(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.SendMessageConfiguration result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        acceptedOutputModes_.makeImmutable();
        result.acceptedOutputModes_ = acceptedOutputModes_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pushNotificationConfig_ = pushNotificationConfigBuilder_ == null
            ? pushNotificationConfig_
            : pushNotificationConfigBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.historyLength_ = historyLength_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.blocking_ = blocking_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.SendMessageConfiguration) {
        return mergeFrom((io.a2a.grpc.SendMessageConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.SendMessageConfiguration other) {
      if (other == io.a2a.grpc.SendMessageConfiguration.getDefaultInstance()) return this;
      if (!other.acceptedOutputModes_.isEmpty()) {
        if (acceptedOutputModes_.isEmpty()) {
          acceptedOutputModes_ = other.acceptedOutputModes_;
          bitField0_ |= 0x00000001;
        } else {
          ensureAcceptedOutputModesIsMutable();
          acceptedOutputModes_.addAll(other.acceptedOutputModes_);
        }
        onChanged();
      }
      if (other.hasPushNotificationConfig()) {
        mergePushNotificationConfig(other.getPushNotificationConfig());
      }
      if (other.hasHistoryLength()) {
        setHistoryLength(other.getHistoryLength());
      }
      if (other.getBlocking() != false) {
        setBlocking(other.getBlocking());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAcceptedOutputModesIsMutable();
              acceptedOutputModes_.add(s);
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetPushNotificationConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              historyLength_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              blocking_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList acceptedOutputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAcceptedOutputModesIsMutable() {
      if (!acceptedOutputModes_.isModifiable()) {
        acceptedOutputModes_ = new com.google.protobuf.LazyStringArrayList(acceptedOutputModes_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @return A list containing the acceptedOutputModes.
     */
    public com.google.protobuf.ProtocolStringList
        getAcceptedOutputModesList() {
      acceptedOutputModes_.makeImmutable();
      return acceptedOutputModes_;
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @return The count of acceptedOutputModes.
     */
    public int getAcceptedOutputModesCount() {
      return acceptedOutputModes_.size();
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @param index The index of the element to return.
     * @return The acceptedOutputModes at the given index.
     */
    public java.lang.String getAcceptedOutputModes(int index) {
      return acceptedOutputModes_.get(index);
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the acceptedOutputModes at the given index.
     */
    public com.google.protobuf.ByteString
        getAcceptedOutputModesBytes(int index) {
      return acceptedOutputModes_.getByteString(index);
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @param index The index to set the value at.
     * @param value The acceptedOutputModes to set.
     * @return This builder for chaining.
     */
    public Builder setAcceptedOutputModes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAcceptedOutputModesIsMutable();
      acceptedOutputModes_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @param value The acceptedOutputModes to add.
     * @return This builder for chaining.
     */
    public Builder addAcceptedOutputModes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAcceptedOutputModesIsMutable();
      acceptedOutputModes_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @param values The acceptedOutputModes to add.
     * @return This builder for chaining.
     */
    public Builder addAllAcceptedOutputModes(
        java.lang.Iterable<java.lang.String> values) {
      ensureAcceptedOutputModesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, acceptedOutputModes_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcceptedOutputModes() {
      acceptedOutputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
     * </pre>
     *
     * <code>repeated string accepted_output_modes = 1;</code>
     * @param value The bytes of the acceptedOutputModes to add.
     * @return This builder for chaining.
     */
    public Builder addAcceptedOutputModesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAcceptedOutputModesIsMutable();
      acceptedOutputModes_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private io.a2a.grpc.PushNotificationConfig pushNotificationConfig_;
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.PushNotificationConfig, io.a2a.grpc.PushNotificationConfig.Builder, io.a2a.grpc.PushNotificationConfigOrBuilder> pushNotificationConfigBuilder_;
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     * @return Whether the pushNotificationConfig field is set.
     */
    public boolean hasPushNotificationConfig() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     * @return The pushNotificationConfig.
     */
    public io.a2a.grpc.PushNotificationConfig getPushNotificationConfig() {
      if (pushNotificationConfigBuilder_ == null) {
        return pushNotificationConfig_ == null ? io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
      } else {
        return pushNotificationConfigBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     */
    public Builder setPushNotificationConfig(io.a2a.grpc.PushNotificationConfig value) {
      if (pushNotificationConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pushNotificationConfig_ = value;
      } else {
        pushNotificationConfigBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     */
    public Builder setPushNotificationConfig(
        io.a2a.grpc.PushNotificationConfig.Builder builderForValue) {
      if (pushNotificationConfigBuilder_ == null) {
        pushNotificationConfig_ = builderForValue.build();
      } else {
        pushNotificationConfigBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     */
    public Builder mergePushNotificationConfig(io.a2a.grpc.PushNotificationConfig value) {
      if (pushNotificationConfigBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pushNotificationConfig_ != null &&
          pushNotificationConfig_ != io.a2a.grpc.PushNotificationConfig.getDefaultInstance()) {
          getPushNotificationConfigBuilder().mergeFrom(value);
        } else {
          pushNotificationConfig_ = value;
        }
      } else {
        pushNotificationConfigBuilder_.mergeFrom(value);
      }
      if (pushNotificationConfig_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     */
    public Builder clearPushNotificationConfig() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pushNotificationConfig_ = null;
      if (pushNotificationConfigBuilder_ != null) {
        pushNotificationConfigBuilder_.dispose();
        pushNotificationConfigBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     */
    public io.a2a.grpc.PushNotificationConfig.Builder getPushNotificationConfigBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetPushNotificationConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     */
    public io.a2a.grpc.PushNotificationConfigOrBuilder getPushNotificationConfigOrBuilder() {
      if (pushNotificationConfigBuilder_ != null) {
        return pushNotificationConfigBuilder_.getMessageOrBuilder();
      } else {
        return pushNotificationConfig_ == null ?
            io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
      }
    }
    /**
     * <pre>
     * Configuration for the agent to send push notifications for task updates.
     * </pre>
     *
     * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.PushNotificationConfig, io.a2a.grpc.PushNotificationConfig.Builder, io.a2a.grpc.PushNotificationConfigOrBuilder> 
        internalGetPushNotificationConfigFieldBuilder() {
      if (pushNotificationConfigBuilder_ == null) {
        pushNotificationConfigBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.PushNotificationConfig, io.a2a.grpc.PushNotificationConfig.Builder, io.a2a.grpc.PushNotificationConfigOrBuilder>(
                getPushNotificationConfig(),
                getParentForChildren(),
                isClean());
        pushNotificationConfig_ = null;
      }
      return pushNotificationConfigBuilder_;
    }

    private int historyLength_ ;
    /**
     * <pre>
     * The maximum number of most recent messages from the task's history to retrieve in
     * the response. An unset value means the client does not impose any limit. A
     * value of zero is a request to not include any messages. The server MUST NOT
     * return more messages than the provided value, but MAY apply a lower limit.
     * </pre>
     *
     * <code>optional int32 history_length = 3;</code>
     * @return Whether the historyLength field is set.
     */
    @java.lang.Override
    public boolean hasHistoryLength() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The maximum number of most recent messages from the task's history to retrieve in
     * the response. An unset value means the client does not impose any limit. A
     * value of zero is a request to not include any messages. The server MUST NOT
     * return more messages than the provided value, but MAY apply a lower limit.
     * </pre>
     *
     * <code>optional int32 history_length = 3;</code>
     * @return The historyLength.
     */
    @java.lang.Override
    public int getHistoryLength() {
      return historyLength_;
    }
    /**
     * <pre>
     * The maximum number of most recent messages from the task's history to retrieve in
     * the response. An unset value means the client does not impose any limit. A
     * value of zero is a request to not include any messages. The server MUST NOT
     * return more messages than the provided value, but MAY apply a lower limit.
     * </pre>
     *
     * <code>optional int32 history_length = 3;</code>
     * @param value The historyLength to set.
     * @return This builder for chaining.
     */
    public Builder setHistoryLength(int value) {

      historyLength_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The maximum number of most recent messages from the task's history to retrieve in
     * the response. An unset value means the client does not impose any limit. A
     * value of zero is a request to not include any messages. The server MUST NOT
     * return more messages than the provided value, but MAY apply a lower limit.
     * </pre>
     *
     * <code>optional int32 history_length = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHistoryLength() {
      bitField0_ = (bitField0_ & ~0x00000004);
      historyLength_ = 0;
      onChanged();
      return this;
    }

    private boolean blocking_ ;
    /**
     * <pre>
     * If true, the operation waits until the task reaches a terminal or interrupted state before returning. Default is false.
     * </pre>
     *
     * <code>bool blocking = 4;</code>
     * @return The blocking.
     */
    @java.lang.Override
    public boolean getBlocking() {
      return blocking_;
    }
    /**
     * <pre>
     * If true, the operation waits until the task reaches a terminal or interrupted state before returning. Default is false.
     * </pre>
     *
     * <code>bool blocking = 4;</code>
     * @param value The blocking to set.
     * @return This builder for chaining.
     */
    public Builder setBlocking(boolean value) {

      blocking_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, the operation waits until the task reaches a terminal or interrupted state before returning. Default is false.
     * </pre>
     *
     * <code>bool blocking = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlocking() {
      bitField0_ = (bitField0_ & ~0x00000008);
      blocking_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.SendMessageConfiguration)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.SendMessageConfiguration)
  private static final io.a2a.grpc.SendMessageConfiguration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.SendMessageConfiguration();
  }

  public static io.a2a.grpc.SendMessageConfiguration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendMessageConfiguration>
      PARSER = new com.google.protobuf.AbstractParser<SendMessageConfiguration>() {
    @java.lang.Override
    public SendMessageConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendMessageConfiguration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendMessageConfiguration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.SendMessageConfiguration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

