// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SendMessageConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SendMessageConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @return A list containing the acceptedOutputModes.
   */
  java.util.List<java.lang.String>
      getAcceptedOutputModesList();
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @return The count of acceptedOutputModes.
   */
  int getAcceptedOutputModesCount();
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @param index The index of the element to return.
   * @return The acceptedOutputModes at the given index.
   */
  java.lang.String getAcceptedOutputModes(int index);
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts. Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the acceptedOutputModes at the given index.
   */
  com.google.protobuf.ByteString
      getAcceptedOutputModesBytes(int index);

  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * </pre>
   *
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
   * @return Whether the pushNotificationConfig field is set.
   */
  boolean hasPushNotificationConfig();
  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * </pre>
   *
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
   * @return The pushNotificationConfig.
   */
  io.a2a.grpc.PushNotificationConfig getPushNotificationConfig();
  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * </pre>
   *
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
   */
  io.a2a.grpc.PushNotificationConfigOrBuilder getPushNotificationConfigOrBuilder();

  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return Whether the historyLength field is set.
   */
  boolean hasHistoryLength();
  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return The historyLength.
   */
  int getHistoryLength();

  /**
   * <pre>
   * If true, the operation waits until the task reaches a terminal or interrupted state before returning. Default is false.
   * </pre>
   *
   * <code>bool blocking = 4;</code>
   * @return The blocking.
   */
  boolean getBlocking();
}
